version: '3'

services:
  server:
    container_name: server
    build:
      context: .docker/php
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html
    networks:
      - corporate
  
  web:
    container_name: web
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8062:80"
    networks:
      - corporate

networks:
  corporate:
    driver: bridge